# Generated by Django 2.2.15 on 2020-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowsays',
            name='cowsays',
            field=models.TextField(max_length=100),
        ),
    ]
